In [2]:
library(data.table, quietly = T)

library(dplyr)

## 
setwd("/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/GWAMA/summary/")

# Annovar Annotated Loci

In [3]:
annot <- fread("annot.unique_varID_hg38_p0001.hg38_multianno.txt.gz", header=TRUE)

head(annot)

  Chr  Start End   Ref Alt Func.refGene Gene.refGene    GeneDetail.refGene
1 chr1 55427 55427 T   C   intergenic   FAM138A;OR4F5   dist=19346;dist=13664
2 chr1 70204 70204 G   T   downstream   OR4F5           dist=196
3 chr1 78286 78286 G   A   intergenic   OR4F5;LOC729737 dist=8278;dist=56487
4 chr1 80094 80094 C   T   intergenic   OR4F5;LOC729737 dist=10086;dist=54679
5 chr1 81038 81038 G   A   intergenic   OR4F5;LOC729737 dist=11030;dist=53735
6 chr1 87421 87421 G   T   intergenic   OR4F5;LOC729737 dist=17413;dist=47352
  ExonicFunc.refGene AAChange.refGene ... Otherinfo2 Otherinfo3 Otherinfo4
1 .                  .                ... .          .          chr1
2 .                  .                ... .          .          chr1
3 .                  .                ... .          .          chr1
4 .                  .                ... .          .          chr1
5 .                  .                ... .          .          chr1
6 .                  .                ... .          .          chr1
  Otherinfo5 Otherinfo6     Otherinfo7 Otherinfo8 Otherinfo9 Otherinfo10
1 55427      chr1:55427:T:C T          C          .          .
2 70204      chr1:70204:G:T G          T          .          .
3 78286      chr1:78286:G:A G          A          .          .
4 80094      chr1:80094:C:T C          T          .          .
5 81038      chr1:81038:G:A G          A          .          .
6 87421      chr1:87421:G:T G          T          .          .
  Otherinfo11
1 .
2 .
3 .
4 .
5 .
6 .

# GWAS / Meta-GWAS Summary

In [4]:
# list GWAS Summary files
gwas_files <- system("ls pval_0.0001*", intern=TRUE)

In [7]:
head(gwas_files)
length(gwas_files)

gwas_files[30]

gwas_files[32]

[1] "pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz"
[2] "pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz"
[3] "pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz"
[4] "pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz"
[5] "pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz"
[6] "pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz"

[1] 113

[1] "pval_0.0001.GWAMA.chr1_22.hasCH.MultiANC.UKBB450k_AoU250k_TOPMed72k_MGBB53k_BioVU54k.tsv.gz"

[1] "pval_0.0001.GWAMA.chr1_22.hasCH.MultiANC.ukbb200k_ukb250k_AoU250k_TOPMed72k_MGBB53k_BioVU54k.tsv.gz"

In [6]:
d <- fread(gwas_files[30], header=T)

head(d)
nrow(d)

###
cat(table(d$SNPID %in% annot$Otherinfo6, exclude=NULL))

###
dat <- merge(d, annot, by.x="SNPID", by.y="Otherinfo6", all.x=TRUE)
head(dat)
nrow(dat)

  SNPID            REF ALT AAF      BETA      SE       BETA_95L  BETA_95U
1 chr1:868281:C:T  T   C   0.999691 -1.575528 0.397759 -2.355136 -0.795920
2 chr1:1655773:T:C C   T   0.999849 -2.185236 0.509012 -3.182900 -1.187572
3 chr1:1822149:G:A A   G   0.999774 -2.171050 0.485233 -3.122107 -1.219993
4 chr1:2103087:C:T T   C   0.999863 -2.553952 0.596937 -3.723949 -1.383955
5 chr1:2266427:A:G G   A   0.999863 -2.553901 0.596944 -3.723911 -1.383891
6 chr1:2641376:G:A A   G   0.999588 -1.482567 0.380189 -2.227737 -0.737397
  Z         P        minusLOG10_P Het_Q Het_P I2  N_Studies N_Samples Direction
1 -3.961012 7.54e-05 4.122802     0     1     NaN 1         72873     ??-??
2 -4.293093 1.78e-05 4.748580     0     1     NaN 1         72877     ??-??
3 -4.474242 7.78e-06 5.109229     0     1     NaN 1         72883     ??-??
4 -4.278428 1.91e-05 4.719980     0     1     NaN 1         72882     ??-??
5 -4.278292 1.91e-05 4.719716     0     1     NaN 1         72881     ??-??
6 -3.899553 9.73e-05 4.011988     0     1     NaN 1         72817     ??-??

[1] 47289

47289

  SNPID                 REF ALT AAF      BETA      SE       BETA_95L  BETA_95U
1 chr10:100011947:G:A   G   A   0.000383  1.931760 0.492086  0.967271  2.896249
2 chr10:100115942:T:G   T   G   0.000381  1.925930 0.492416  0.960795  2.891065
3 chr10:100352521:G:A   A   G   0.999856 -2.228318 0.549310 -3.304966 -1.151670
4 chr10:100364207:CTG:C CTG C   0.000347  1.985205 0.482421  1.039660  2.930750
5 chr10:100553939:C:G   C   G   0.000084  1.746873 0.435020  0.894234  2.599512
6 chr10:100627293:C:T   C   T   0.000220  1.136529 0.259093  0.628707  1.644351
  Z         P        ... Otherinfo1 Otherinfo2 Otherinfo3 Otherinfo4 Otherinfo5
1  3.925655 8.73e-05 ... .          .          .          chr10      100011947
2  3.911185 9.27e-05 ... .          .          .          chr10      100115942
3 -4.056576 5.03e-05 ... .          .          .          chr10      100352521
4  4.115088 3.91e-05 ... .          .          .          chr10      100364207
5  4.015615 5.99e-05 ... .          .          .          chr10      100553939
6  4.386569 1.17e-05 ... .          .          .          chr10      100627293
  Otherinfo7 Otherinfo8 Otherinfo9 Otherinfo10 Otherinfo11
1 G          A          .          .           .
2 T          G          .          .           .
3 G          A          .          .           .
4 CTG        C          .          .           .
5 C          G          .          .           .
6 C          T          .          .           .

[1] 47289

In [15]:
i=1
paste0("annovar.",
       gsub(pattern = "tsv.gz", 
            replacement = "csv", 
            x = gwas_files[i]) )


paste0("/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/GWAMA/summary/annovar/annovar.", 
       gsub(pattern = "tsv.gz", 
            replacement = "csv", 
            x = gwas_files[i]))

[1] "annovar.pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.csv"

[1] "/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/GWAMA/summary/annovar/annovar.pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.csv"

# Annotate

In [18]:
rm(d)

for(i in 1:length(gwas_files)){
    
    ##
    cat(i,"\n")
    cat(gwas_files[i], "\n")
    ##

    d <- fread(gwas_files[i], header=T)
    
    print(head(d))
    cat("\n")
    cat(nrow(d), "\n")

###
    cat(table(d$SNPID %in% annot$Otherinfo6, exclude=NULL), "\n")

###
    dat <- merge(d, annot, 
                 by.x="SNPID", 
                 by.y="Otherinfo6", 
                 all.x=TRUE)
    cat(nrow(dat), "\n")    
    
###
    outfile_name <- paste0("/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/GWAMA/summary/annovar/annovar.", 
                           gsub(pattern = "tsv.gz", 
                           replacement = "csv", 
                           x = gwas_files[i]))
    
    fwrite(x = dat, file = outfile_name, 
           row.names = FALSE, 
           col.names = TRUE, 
           sep=",", 
           quote=TRUE)
    ##
    rm(dat)
    
}

1
pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
               SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:   chr1:922263:G:A   A   G 0.999149 -3.095402 0.794578 -4.652775 -1.538029
2:  chr1:1018367:C:T   T   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
3:  chr1:1020894:G:C   C   G 0.999422 -3.716390 0.945653 -5.569870 -1.862910
4:  chr1:1037333:C:G   G   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
5:  chr1:1100572:C:G   G   C 0.999095 -3.747777 0.905251 -5.522069 -1.973485
6: chr1:1150280:AG:A   A  AG 0.999451 -4.274670 1.026446 -6.286504 -2.262836
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -3.895655 9.89e-05     4.005014     0     1 NaN         1     18220
2: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18221
3: -3.929972 8.58e-05     4.066642     0     1   0         1     18153
4: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18222
5: -4.140042 3.51e-05     4.454495     0     1 NaN         1     18223
6: -4.164535 3.16e-05     4.500904     0     1 NaN         1     18210
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

86309
86309
86309
2
pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:   chr1:55427:T:C   T   C 0.006066  1.565527 0.361530  0.856928  2.274126
2:   chr1:87421:G:T   G   T 0.001070  2.297891 0.514283  1.289896  3.305886
3:   chr1:94970:C:T   C   T 0.001290  2.141355 0.476541  1.207335  3.075375
4:  chr1:922263:G:A   A   G 0.999149 -3.095402 0.794578 -4.652775 -1.538029
5: chr1:1018367:C:T   T   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
6: chr1:1020894:G:C   C   G 0.999422 -3.716390 0.945653 -5.569870 -1.862910
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1:  4.330282 1.51e-05     4.821507     0     1 NaN         1     41956
2:  4.468145 8.00e-06     5.096868     0     1 NaN         1     43443
3:  4.493538 7.10e-06     5.148450     0     1 NaN         1     43810
4: -3.895655 9.89e-05     4.005014     0     1 NaN         1     18220
5: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18221
6: -3.929972 8.58e-05     4.066642     0     1   0         1     18153
   Direction
1:      ?+??
2:      ?+??
3:      ?+??
4:      ??-?
5:      ??-?
6:      ??-?

90101
90101
90101
3
pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:768968:C:T   T   C 0.998615 -3.768046 0.956303 -5.642400 -1.893692
2: chr1:1381907:G:A   A   G 0.998436 -4.229041 1.047881 -6.282888 -2.175194
3: chr1:1452554:G:C   C   G 0.998044 -3.108008 0.790348 -4.657090 -1.558926
4: chr1:1487254:C:T   T   C 0.998369 -4.219628 1.044464 -6.266777 -2.172479
5: chr1:1538006:G:A   A   G 0.998436 -4.225581 1.046601 -6.276919 -2.174243
6: chr1:2112271:C:A   A   C 0.998632 -3.609548 0.923263 -5.419143 -1.799953
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -3.940222 8.22e-05     4.085143     0     1 NaN         1      7582
2: -4.035803 5.50e-05     4.259757     0     1 NaN         1      7673
3: -3.932455 8.49e-05     4.071119     0     1 NaN         1      7667
4: -4.039994 5.40e-05     4.267500     0     1 NaN         1      7663
5: -4.037433 5.46e-05     4.262767     0     1 NaN         1      7673
6: -3.909556 9.33e-05     4.029918     0     1 NaN         1      7673
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

30242
30242
30242
4
pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
                  SNPID   REF ALT      AAF      BETA       SE  BETA_95L
1:      chr1:768968:C:T     T   C 0.998615 -3.768046 0.956303 -5.642400
2:      chr1:978225:C:T     C   T 0.002936  4.733486 1.166920  2.446323
3:     chr1:1192820:G:A     G   A 0.002609  3.014204 0.691412  1.659036
4:     chr1:1207207:G:A     G   A 0.001921  3.426385 0.641773  2.168510
5: chr1:1221953:AAAAG:A AAAAG   A 0.001606  3.189654 0.792666  1.636029
6:     chr1:1243468:G:A     G   A 0.001858  3.300963 0.747688  1.835496
    BETA_95U         Z        P minusLOG10_P    Het_Q    Het_P       I2
1: -1.893692 -3.940222 8.22e-05     4.085143 0.000000 1.000000      NaN
2:  7.020649  4.056393 5.04e-05     4.297868 0.936726 0.333121 0.000000
3:  4.369372  4.359490 1.32e-05     4.879186 0.000000 1.000000      NaN
4:  4.684260  5.338936 9.56e-08     7.019712 0.000000 1.000000      NaN
5:  4.743279  4.023957 5.78e-05     4.237912 2.636615 0.104426 0.620726
6:  4.766431  4.414897 1.02e-05     4.989575 1.770101 0.183370 0.435060
   N_Studies N_Samples Direction
1:         1      7582      ??-?
2:         2     39243      ?+?+
3:         1     30285      ?+??
4:         1     35914      ?+??
5:         2     43587      ?-+?
6:         2     43588      ?++?

32565
32565
32565
5
pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
                 SNPID REF  ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:    chr1:1091539:G:A   A    G 0.999736 -3.380540 0.740564 -4.832045 -1.929035
2:    chr1:1159165:A:G   G    A 0.999644 -2.935615 0.743929 -4.393716 -1.477514
3:    chr1:1182739:G:A   A    G 0.999631 -2.972972 0.762393 -4.467262 -1.478681
4:    chr1:1203315:C:T   T    C 0.999617 -3.602360 0.811457 -5.192816 -2.011904
5:    chr1:1254595:G:A   A    G 0.999617 -3.437272 0.868261 -5.139064 -1.735480
6: chr1:1266828:AAAT:A   A AAAT 0.998527 -1.912470 0.423309 -2.742156 -1.082784
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.564818 5.07e-06     5.294680 0.000000 1.000000      NaN         1
2: -3.946096 8.02e-05     4.095765 0.000000 1.000000      NaN         1
3: -3.899526 9.73e-05     4.011941 0.111421 0.738532 0.000000         2
4: -4.439373 9.15e-06     5.038746 0.000000 1.000000      NaN         1
5: -3.958800 7.61e-05     4.118788 0.000000 1.000000      NaN         1
6: -4.517904 6.34e-06     5.198198 1.568439 0.210434 0.362423         2
   N_Samples Direction
1:     37880       ?-?
2:     37884       ?-?
3:     75662       ?--
4:     37876       ?-?
5:     37881       ?-?
6:     75664       ?--

51327
51327
51327
6
pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:1126159:C:T   C   T 0.000038 2.755898 0.705637 1.372849 4.138947
2: chr1:1143606:G:A   G   A 0.000145 2.290563 0.547329 1.217798 3.363328
3: chr1:1147746:G:A   G   A 0.000042 3.797108 0.794134 2.240605 5.353611
4: chr1:1171708:G:A   G   A 0.000506 1.349660 0.340715 0.681858 2.017462
5: chr1:1172226:G:A   G   A 0.000281 2.233030 0.527918 1.198311 3.267749
6: chr1:1180415:G:A   G   A 0.000042 3.000572 0.768786 1.493751 4.507393
          Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: 3.905546 9.49e-05     4.022727 0.000000 1.000000      NaN         1
2: 4.184984 2.89e-05     4.539842 0.000000 1.000000      NaN         1
3: 4.781445 1.77e-06     5.752105 0.000000 1.000000 0.000000         1
4: 3.961257 7.53e-05     4.123247 7.481134 0.023741 0.732661         3
5: 4.229883 2.37e-05     4.625944 0.787791 0.374769 0.000000         2
6: 3.903000 9.59e-05     4.018164 0.000000 1.000000 0.000000         1
   N_Samples Direction
1:    388018      +???
2:    388018      +???
3:    388018      +???
4:    463667      +?+-
5:    425899      +?+?
6:    388018      +???

244294
244294
244294
7
pval_0.0001.GWAMA.chr1_22.hasASXL1.Female.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:769499:G:C   G   C 0.000522  4.195042 1.045107  2.146632  6.243452
2: chr1:780466:G:A   A   G 0.998762 -2.922156 0.627831 -4.152704 -1.691607
3: chr1:793267:C:T   T   C 0.998779 -2.922419 0.624943 -4.147307 -1.697531
4: chr1:794072:C:T   T   C 0.998787 -2.933263 0.626271 -4.160754 -1.705772
5: chr1:795717:G:A   A   G 0.998779 -2.913844 0.627522 -4.143786 -1.683902
6: chr1:796639:C:T   T   C 0.998779 -2.922420 0.624943 -4.147308 -1.697532
           Z        P minusLOG10_P    Het_Q    Het_P  I2 N_Studies N_Samples
1:  4.013983 6.03e-05     4.219563 0.000000 1.000000 NaN         1     25335
2: -4.654367 3.30e-06     5.481392 0.435123 0.509486   0         2     66395
3: -4.676298 2.97e-06     5.527630 0.383258 0.535865   0         2     66396
4: -4.683696 2.86e-06     5.543272 0.417528 0.518173   0         2     66396
5: -4.643416 3.48e-06     5.458380 0.446790 0.503863   0         2     66398
6: -4.676299 2.97e-06     5.527632 0.383257 0.535865   0         2     66397
   Direction
1:       ??+
2:       ?--
3:       ?--
4:       ?--
5:       ?--
6:       ?--

220139
220139
220139
8
pval_0.0001.GWAMA.chr1_22.hasASXL1.Female.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:824903:C:G   C   G 0.000418 3.013057 0.644678 1.749489 4.276625
2: chr1:825872:C:T   C   T 0.000481 2.759369 0.642608 1.499857 4.018881
3: chr1:829566:T:C   T   C 0.000414 3.015629 0.645013 1.751405 4.279854
4: chr1:832823:C:T   C   T 0.000438 3.495835 0.891218 1.749047 5.242622
5: chr1:837890:G:T   G   T 0.000447 2.995344 0.641076 1.738835 4.251854
6: chr1:841202:A:G   A   G 0.000416 3.014542 0.644780 1.750774 4.278310
          Z        P minusLOG10_P    Het_Q    Het_P      I2 N_Studies N_Samples
1: 4.673742 3.00e-06     5.522232 0.618324 0.734062 0.00000         3    287583
2: 4.294014 1.78e-05     4.750378 1.079622 0.582858 0.00000         3    287583
3: 4.675303 2.98e-06     5.525527 0.606722 0.738333 0.00000         3    287581
4: 3.922535 8.85e-05     4.053245 2.326556 0.312460 0.14036         3    287525
5: 4.672367 3.02e-06     5.519328 0.623087 0.732316 0.00000         3    287576
6: 4.675305 2.98e-06     5.525533 0.610431 0.736964 0.00000         3    287583
   Direction
1:      +?++
2:      +?++
3:      +?++
4:      +?++
5:      +?++
6:      +?++

298176
298176
298176
9
pval_0.0001.GWAMA.chr1_22.hasASXL1.Male.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:776729:C:G   G   C 0.999596 -3.675855 0.906064 -5.451740 -1.899970
2:  chr1:835427:C:G   G   C 0.998186 -2.750612 0.616365 -3.958687 -1.542537
3:  chr1:968677:G:C   C   G 0.999528 -2.933646 0.677918 -4.262365 -1.604927
4:  chr1:975749:G:A   A   G 0.999601 -3.697585 0.947577 -5.554836 -1.840334
5: chr1:1065477:G:A   A   G 0.999582 -3.695773 0.670812 -5.010565 -2.380981
6: chr1:1065478:C:A   A   C 0.999601 -3.494938 0.753512 -4.971822 -2.018054
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.056949 5.02e-05     4.298898     0     1 NaN         1     27239
2: -4.462635 8.21e-06     5.085711     0     1 NaN         1     27556
3: -4.327435 1.53e-05     4.815903     0     1 NaN         1     27556
4: -3.902147 9.62e-05     4.016635     0     1 NaN         1     27552
5: -5.509402 3.69e-08     7.433409     0     1 NaN         1     27541
6: -4.638198 3.57e-06     5.447433     0     1 NaN         1     27541
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

90597
90597
90597
10
pval_0.0001.GWAMA.chr1_22.hasASXL1.Male.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:776729:C:G   G   C 0.999596 -3.675855 0.906064 -5.451740 -1.899970
2:  chr1:823032:C:T   C   T 0.006931  1.053056 0.264518  0.534601  1.571511
3:  chr1:834901:T:A   T   A 0.001039  1.771236 0.444135  0.900731  2.641741
4:  chr1:968677:G:C   C   G 0.999528 -2.933646 0.677918 -4.262365 -1.604927
5: chr1:1065477:G:A   A   G 0.999582 -3.695773 0.670812 -5.010565 -2.380981
6: chr1:1065478:C:A   A   C 0.999601 -3.494938 0.753512 -4.971822 -2.018054
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.056949 5.02e-05     4.298898     0     1 NaN         1     27239
2:  3.981037 6.93e-05     4.159246     0     1 NaN         1     85340
3:  3.988058 6.73e-05     4.172061     0     1   0         1     86172
4: -4.327435 1.53e-05     4.815903     0     1 NaN         1     27556
5: -5.509402 3.69e-08     7.433409     0     1 NaN         1     27541
6: -4.638198 3.57e-06     5.447433     0     1 NaN         1     27541
   Direction
1:      ??-?
2:      ?+??
3:      ?+??
4:      ??-?
5:      ??-?
6:      ??-?

138126
138126
138126
11
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
3: chr1:835427:C:G   G   C 0.998818 -2.351023 0.554729 -3.438292 -1.263753
4: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
5: chr1:855362:C:T   T   C 0.999811 -3.836126 0.770500 -5.346306 -2.325946
6: chr1:905992:G:A   A   G 0.999811 -3.610069 0.900788 -5.375613 -1.844525
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.024650 5.77e-05     4.239187 0.000000 1.000000      NaN         1
2: -4.093935 4.29e-05     4.367804 0.000000 1.000000 0.000000         1
3: -4.238144 2.28e-05     4.641879 2.162101 0.141451 0.537487         2
4: -4.172480 3.05e-05     4.516012 0.000000 1.000000      NaN         1
5: -4.978749 6.52e-07     6.185814 0.000000 1.000000      NaN         1
6: -4.007679 6.19e-05     4.207986 0.000000 1.000000      NaN         1
   N_Samples Direction
1:     68595       ?-?
2:     68614       ?-?
3:    113865       ?-+
4:     68615       ?-?
5:     68617       ?-?
6:     68603       ?-?

249715
249715
249715
12
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.UKBB450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
3: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
4: chr1:905992:G:A   A   G 0.999811 -3.610069 0.900788 -5.375613 -1.844525
5: chr1:917006:C:T   T   C 0.999577 -2.830286 0.695489 -4.193444 -1.467128
6: chr1:944681:C:T   T   C 0.999665 -3.717924 0.701207 -5.092290 -2.343558
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.024650 5.77e-05     4.239187     0     1 NaN         1     68595
2: -4.093935 4.29e-05     4.367804     0     1   0         1     68614
3: -4.172480 3.05e-05     4.516012     0     1 NaN         1     68615
4: -4.007679 6.19e-05     4.207986     0     1 NaN         1     68603
5: -4.069491 4.76e-05     4.322201     0     1 NaN         1     68616
6: -5.302178 1.17e-07     6.932109     0     1 NaN         1     68614
   Direction
1:      ??-?
2:      ??-?
3:      ??-?
4:      ??-?
5:      ??-?
6:      ??-?

473297
473297
473297
13
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.ukbb200k_ukb250k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:826742:T:C   T   C 0.000049  3.457193 0.792858  1.903191  5.011195
3: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
4: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
5: chr1:849938:T:C   T   C 0.000045  3.263489 0.747890  1.797625  4.729353
6: chr1:851048:G:T   G   T 0.000240  2.681253 0.506355  1.688797  3.673708
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.024650 5.77e-05     4.239187 0.000000 1.000000      NaN         1
2:  4.360419 1.32e-05     4.881025 0.000000 1.000000      NaN         1
3: -4.093935 4.29e-05     4.367804 0.000000 1.000000 0.000000         1
4: -4.172480 3.05e-05     4.516012 0.000000 1.000000      NaN         1
5:  4.363595 1.30e-05     4.887319 0.000000 1.000000      NaN         1
6:  5.295205 1.21e-07     6.915556 2.697433 0.259573 0.258554         3
   N_Samples Direction
1:     68595     ???-?
2:    227291     ?+???
3:     68614     ???-?
4:     68615     ???-?
5:    227291     ?+???
6:    341154     ?+?+-

523713
523713
523713
14
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.ukbb450k.ukb200k_N193342.ukb250k_N243350.tsv.gz
             SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:826742:T:C   T   C 0.000049 3.457193 0.792858 1.903191 5.011195
2: chr1:849938:T:C   T   C 0.000045 3.263489 0.747890 1.797625 4.729353
3: chr1:851048:G:T   G   T 0.000046 3.728087 0.945507 1.874893 5.581281
4: chr1:898406:C:T   C   T 0.000047 3.107279 0.775660 1.586985 4.627573
5: chr1:936104:C:T   C   T 0.000048 4.191775 0.826222 2.572380 5.811170
6: chr1:986717:C:T   C   T 0.000309 2.465500 0.589411 1.310254 3.620747
          Z        P minusLOG10_P    Het_Q    Het_P  I2 N_Studies N_Samples
1: 4.360419 1.32e-05     4.881025 0.000000 1.000000 NaN         1    227291
2: 4.363595 1.30e-05     4.887319 0.000000 1.000000 NaN         1    227291
3: 3.942950 8.13e-05     4.090075 0.000000 1.000000 NaN         1    227291
4: 4.005981 6.24e-05     4.204871 0.000000 1.000000   0         1    227291
5: 5.073425 3.98e-07     6.399723 0.000000 1.000000 NaN         1    227291
6: 4.182987 2.91e-05     4.536033 0.771214 0.379842   0         2    409711
   Direction
1:        ?+
2:        ?+
3:        ?+
4:        ?+
5:        ?+
6:        ++

369990
369990
369990
15
pval_0.0001.GWAMA.chr1_22.hasCH.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:969341:A:T   T   A 0.999295 -2.162973 0.534084 -3.209778 -1.116168
2: chr1:1051696:C:T   T   C 0.999425 -2.286489 0.581976 -3.427162 -1.145816
3: chr1:1686316:T:C   C   T 0.998120 -1.416984 0.358953 -2.120532 -0.713436
4: chr1:2925163:G:A   A   G 0.999452 -2.253087 0.542778 -3.316932 -1.189242
5: chr1:2947500:C:T   T   C 0.999452 -2.253072 0.542779 -3.316919 -1.189225
6: chr1:2961747:C:A   A   C 0.999373 -2.149339 0.526925 -3.182112 -1.116566
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.049874 5.18e-05     4.285783     0     1 NaN         1     19150
2: -3.928837 8.62e-05     4.064596     0     1 NaN         1     19146
3: -3.947547 7.97e-05     4.098392     0     1 NaN         1     19146
4: -4.151029 3.35e-05     4.475282     0     1 NaN         1     19147
5: -4.150993 3.35e-05     4.475215     0     1 NaN         1     19150
6: -4.079023 4.57e-05     4.339954     0     1 NaN         1     19145
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

14960
14960
14960
16
pval_0.0001.GWAMA.chr1_22.hasCH.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:969341:A:T   T   A 0.999295 -2.162973 0.534084 -3.209778 -1.116168
2: chr1:1051696:C:T   T   C 0.999425 -2.286489 0.581976 -3.427162 -1.145816
3: chr1:2925163:G:A   A   G 0.999452 -2.253087 0.542778 -3.316932 -1.189242
4: chr1:2947500:C:T   T   C 0.999452 -2.253072 0.542779 -3.316919 -1.189225
5: chr1:2961747:C:A   A   C 0.999373 -2.149339 0.526925 -3.182112 -1.116566
6: chr1:3243226:C:T   C   T 0.001738  1.019734 0.244823  0.539882  1.499587
           Z        P minusLOG10_P    Het_Q   Het_P       I2 N_Studies
1: -4.049874 5.18e-05     4.285783 0.000000 1.00000      NaN         1
2: -3.928837 8.62e-05     4.064596 0.000000 1.00000      NaN         1
3: -4.151029 3.35e-05     4.475282 0.000000 1.00000      NaN         1
4: -4.150993 3.35e-05     4.475215 0.000000 1.00000      NaN         1
5: -4.079023 4.57e-05     4.339954 0.000000 1.00000      NaN         1
6:  4.165198 3.15e-05     4.502165 6.486473 0.01087 0.845833         2

## EAF>0.1%

In [25]:
rm(dat, d, outfile_name)
for(i in 1:length(gwas_files)){
    
    ##
    cat(i,"\n")
    cat(gwas_files[i], "\n")
    ##

    d <- fread(gwas_files[i], header=T)
    
    print(head(d))
    cat("\n")
    cat("#SNP in GWAS Summary: ",nrow(d), "\n")

###
    cat("Overall with Annotation: ",table(d$SNPID %in% annot$Otherinfo6, exclude=NULL), "\n")

###
    dat <- merge(d, annot, 
                 by.x="SNPID", 
                 by.y="Otherinfo6", 
                 all.x=TRUE)
    cat("Combined ",nrow(dat), "\n")    
    
    dat <- dat %>% filter(AAF>0.001 & AAF<0.999 & P<5e-7)
    
    cat(nrow(dat), "\n")
###
    outfile_name <- paste0("/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/GWAMA/summary/annovar/eaf001/eaf001p5e7.annovar.", 
                           gsub(pattern = "tsv.gz", 
                           replacement = "csv", 
                           x = gwas_files[i]))
    
    fwrite(x = dat, file = outfile_name, 
           row.names = FALSE, 
           col.names = TRUE, 
           sep=",", 
           quote=TRUE)
    ##
    rm(dat, d, outfile_name)
    
}

Warning message in rm(dat, d, outfile_name):
"object 'dat' not found"
Warning message in rm(dat, d, outfile_name):
"object 'outfile_name' not found"

1
pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
               SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:   chr1:922263:G:A   A   G 0.999149 -3.095402 0.794578 -4.652775 -1.538029
2:  chr1:1018367:C:T   T   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
3:  chr1:1020894:G:C   C   G 0.999422 -3.716390 0.945653 -5.569870 -1.862910
4:  chr1:1037333:C:G   G   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
5:  chr1:1100572:C:G   G   C 0.999095 -3.747777 0.905251 -5.522069 -1.973485
6: chr1:1150280:AG:A   A  AG 0.999451 -4.274670 1.026446 -6.286504 -2.262836
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -3.895655 9.89e-05     4.005014     0     1 NaN         1     18220
2: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18221
3: -3.929972 8.58e-05     4.066642     0     1   0         1     18153
4: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18222
5: -4.140042 3.51e-05     4.454495     0     1 NaN         1     18223
6: -4.164535 3.16e-05     4.500904     0     1 NaN         1     18210
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  86309
Overall with Annotation:  86309
Combined  86309
2743
2
pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:   chr1:55427:T:C   T   C 0.006066  1.565527 0.361530  0.856928  2.274126
2:   chr1:87421:G:T   G   T 0.001070  2.297891 0.514283  1.289896  3.305886
3:   chr1:94970:C:T   C   T 0.001290  2.141355 0.476541  1.207335  3.075375
4:  chr1:922263:G:A   A   G 0.999149 -3.095402 0.794578 -4.652775 -1.538029
5: chr1:1018367:C:T   T   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
6: chr1:1020894:G:C   C   G 0.999422 -3.716390 0.945653 -5.569870 -1.862910
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1:  4.330282 1.51e-05     4.821507     0     1 NaN         1     41956
2:  4.468145 8.00e-06     5.096868     0     1 NaN         1     43443
3:  4.493538 7.10e-06     5.148450     0     1 NaN         1     43810
4: -3.895655 9.89e-05     4.005014     0     1 NaN         1     18220
5: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18221
6: -3.929972 8.58e-05     4.066642     0     1   0         1     18153
   Direction
1:      ?+??
2:      ?+??
3:      ?+??
4:      ??-?
5:      ??-?
6:      ??-?

#SNP in GWAS Summary:  90101
Overall with Annotation:  90101
Combined  90101
3033
3
pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:768968:C:T   T   C 0.998615 -3.768046 0.956303 -5.642400 -1.893692
2: chr1:1381907:G:A   A   G 0.998436 -4.229041 1.047881 -6.282888 -2.175194
3: chr1:1452554:G:C   C   G 0.998044 -3.108008 0.790348 -4.657090 -1.558926
4: chr1:1487254:C:T   T   C 0.998369 -4.219628 1.044464 -6.266777 -2.172479
5: chr1:1538006:G:A   A   G 0.998436 -4.225581 1.046601 -6.276919 -2.174243
6: chr1:2112271:C:A   A   C 0.998632 -3.609548 0.923263 -5.419143 -1.799953
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -3.940222 8.22e-05     4.085143     0     1 NaN         1      7582
2: -4.035803 5.50e-05     4.259757     0     1 NaN         1      7673
3: -3.932455 8.49e-05     4.071119     0     1 NaN         1      7667
4: -4.039994 5.40e-05     4.267500     0     1 NaN         1      7663
5: -4.037433 5.46e-05     4.262767     0     1 NaN         1      7673
6: -3.909556 9.33e-05     4.029918     0     1 NaN         1      7673
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  30242
Overall with Annotation:  30242
Combined  30242
1077
4
pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
                  SNPID   REF ALT      AAF      BETA       SE  BETA_95L
1:      chr1:768968:C:T     T   C 0.998615 -3.768046 0.956303 -5.642400
2:      chr1:978225:C:T     C   T 0.002936  4.733486 1.166920  2.446323
3:     chr1:1192820:G:A     G   A 0.002609  3.014204 0.691412  1.659036
4:     chr1:1207207:G:A     G   A 0.001921  3.426385 0.641773  2.168510
5: chr1:1221953:AAAAG:A AAAAG   A 0.001606  3.189654 0.792666  1.636029
6:     chr1:1243468:G:A     G   A 0.001858  3.300963 0.747688  1.835496
    BETA_95U         Z        P minusLOG10_P    Het_Q    Het_P       I2
1: -1.893692 -3.940222 8.22e-05     4.085143 0.000000 1.000000      NaN
2:  7.020649  4.056393 5.04e-05     4.297868 0.936726 0.333121 0.000000
3:  4.369372  4.359490 1.32e-05     4.879186 0.000000 1.000000      NaN
4:  4.684260  5.338936 9.56e-08     7.019712 0.000000 1.000000      NaN
5:  4.743279  4.023957 5.78e-05     4.237912 2.636615 0.104426 0.620726
6:  4.766431  4.414897 1.02e-05     4.989575 1.770101 0.183370 0.435060
   N_Studies N_Samples Direction
1:         1      7582      ??-?
2:         2     39243      ?+?+
3:         1     30285      ?+??
4:         1     35914      ?+??
5:         2     43587      ?-+?
6:         2     43588      ?++?

#SNP in GWAS Summary:  32565
Overall with Annotation:  32565
Combined  32565
1395
5
pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
                 SNPID REF  ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:    chr1:1091539:G:A   A    G 0.999736 -3.380540 0.740564 -4.832045 -1.929035
2:    chr1:1159165:A:G   G    A 0.999644 -2.935615 0.743929 -4.393716 -1.477514
3:    chr1:1182739:G:A   A    G 0.999631 -2.972972 0.762393 -4.467262 -1.478681
4:    chr1:1203315:C:T   T    C 0.999617 -3.602360 0.811457 -5.192816 -2.011904
5:    chr1:1254595:G:A   A    G 0.999617 -3.437272 0.868261 -5.139064 -1.735480
6: chr1:1266828:AAAT:A   A AAAT 0.998527 -1.912470 0.423309 -2.742156 -1.082784
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.564818 5.07e-06     5.294680 0.000000 1.000000      NaN         1
2: -3.946096 8.02e-05     4.095765 0.000000 1.000000      NaN         1
3: -3.899526 9.73e-05     4.011941 0.111421 0.738532 0.000000         2
4: -4.439373 9.15e-06     5.038746 0.000000 1.000000      NaN         1
5: -3.958800 7.61e-05     4.118788 0.000000 1.000000      NaN         1
6: -4.517904 6.34e-06     5.198198 1.568439 0.210434 0.362423         2
   N_Samples Direction
1:     37880       ?-?
2:     37884       ?-?
3:     75662       ?--
4:     37876       ?-?
5:     37881       ?-?
6:     75664       ?--

#SNP in GWAS Summary:  51327
Overall with Annotation:  51327
Combined  51327
644
6
pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:1126159:C:T   C   T 0.000038 2.755898 0.705637 1.372849 4.138947
2: chr1:1143606:G:A   G   A 0.000145 2.290563 0.547329 1.217798 3.363328
3: chr1:1147746:G:A   G   A 0.000042 3.797108 0.794134 2.240605 5.353611
4: chr1:1171708:G:A   G   A 0.000506 1.349660 0.340715 0.681858 2.017462
5: chr1:1172226:G:A   G   A 0.000281 2.233030 0.527918 1.198311 3.267749
6: chr1:1180415:G:A   G   A 0.000042 3.000572 0.768786 1.493751 4.507393
          Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: 3.905546 9.49e-05     4.022727 0.000000 1.000000      NaN         1
2: 4.184984 2.89e-05     4.539842 0.000000 1.000000      NaN         1
3: 4.781445 1.77e-06     5.752105 0.000000 1.000000 0.000000         1
4: 3.961257 7.53e-05     4.123247 7.481134 0.023741 0.732661         3
5: 4.229883 2.37e-05     4.625944 0.787791 0.374769 0.000000         2
6: 3.903000 9.59e-05     4.018164 0.000000 1.000000 0.000000         1
   N_Samples Direction
1:    388018      +???
2:    388018      +???
3:    388018      +???
4:    463667      +?+-
5:    425899      +?+?
6:    388018      +???

#SNP in GWAS Summary:  244294
Overall with Annotation:  244294
Combined  244294
385
7
pval_0.0001.GWAMA.chr1_22.hasASXL1.Female.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:769499:G:C   G   C 0.000522  4.195042 1.045107  2.146632  6.243452
2: chr1:780466:G:A   A   G 0.998762 -2.922156 0.627831 -4.152704 -1.691607
3: chr1:793267:C:T   T   C 0.998779 -2.922419 0.624943 -4.147307 -1.697531
4: chr1:794072:C:T   T   C 0.998787 -2.933263 0.626271 -4.160754 -1.705772
5: chr1:795717:G:A   A   G 0.998779 -2.913844 0.627522 -4.143786 -1.683902
6: chr1:796639:C:T   T   C 0.998779 -2.922420 0.624943 -4.147308 -1.697532
           Z        P minusLOG10_P    Het_Q    Het_P  I2 N_Studies N_Samples
1:  4.013983 6.03e-05     4.219563 0.000000 1.000000 NaN         1     25335
2: -4.654367 3.30e-06     5.481392 0.435123 0.509486   0         2     66395
3: -4.676298 2.97e-06     5.527630 0.383258 0.535865   0         2     66396
4: -4.683696 2.86e-06     5.543272 0.417528 0.518173   0         2     66396
5: -4.643416 3.48e-06     5.458380 0.446790 0.503863   0         2     66398
6: -4.676299 2.97e-06     5.527632 0.383257 0.535865   0         2     66397
   Direction
1:       ??+
2:       ?--
3:       ?--
4:       ?--
5:       ?--
6:       ?--

#SNP in GWAS Summary:  220139
Overall with Annotation:  220139
Combined  220139
6052
8
pval_0.0001.GWAMA.chr1_22.hasASXL1.Female.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:824903:C:G   C   G 0.000418 3.013057 0.644678 1.749489 4.276625
2: chr1:825872:C:T   C   T 0.000481 2.759369 0.642608 1.499857 4.018881
3: chr1:829566:T:C   T   C 0.000414 3.015629 0.645013 1.751405 4.279854
4: chr1:832823:C:T   C   T 0.000438 3.495835 0.891218 1.749047 5.242622
5: chr1:837890:G:T   G   T 0.000447 2.995344 0.641076 1.738835 4.251854
6: chr1:841202:A:G   A   G 0.000416 3.014542 0.644780 1.750774 4.278310
          Z        P minusLOG10_P    Het_Q    Het_P      I2 N_Studies N_Samples
1: 4.673742 3.00e-06     5.522232 0.618324 0.734062 0.00000         3    287583
2: 4.294014 1.78e-05     4.750378 1.079622 0.582858 0.00000         3    287583
3: 4.675303 2.98e-06     5.525527 0.606722 0.738333 0.00000         3    287581
4: 3.922535 8.85e-05     4.053245 2.326556 0.312460 0.14036         3    287525
5: 4.672367 3.02e-06     5.519328 0.623087 0.732316 0.00000         3    287576
6: 4.675305 2.98e-06     5.525533 0.610431 0.736964 0.00000         3    287583
   Direction
1:      +?++
2:      +?++
3:      +?++
4:      +?++
5:      +?++
6:      +?++

#SNP in GWAS Summary:  298176
Overall with Annotation:  298176
Combined  298176
4266
9
pval_0.0001.GWAMA.chr1_22.hasASXL1.Male.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:776729:C:G   G   C 0.999596 -3.675855 0.906064 -5.451740 -1.899970
2:  chr1:835427:C:G   G   C 0.998186 -2.750612 0.616365 -3.958687 -1.542537
3:  chr1:968677:G:C   C   G 0.999528 -2.933646 0.677918 -4.262365 -1.604927
4:  chr1:975749:G:A   A   G 0.999601 -3.697585 0.947577 -5.554836 -1.840334
5: chr1:1065477:G:A   A   G 0.999582 -3.695773 0.670812 -5.010565 -2.380981
6: chr1:1065478:C:A   A   C 0.999601 -3.494938 0.753512 -4.971822 -2.018054
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.056949 5.02e-05     4.298898     0     1 NaN         1     27239
2: -4.462635 8.21e-06     5.085711     0     1 NaN         1     27556
3: -4.327435 1.53e-05     4.815903     0     1 NaN         1     27556
4: -3.902147 9.62e-05     4.016635     0     1 NaN         1     27552
5: -5.509402 3.69e-08     7.433409     0     1 NaN         1     27541
6: -4.638198 3.57e-06     5.447433     0     1 NaN         1     27541
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  90597
Overall with Annotation:  90597
Combined  90597
2534
10
pval_0.0001.GWAMA.chr1_22.hasASXL1.Male.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:776729:C:G   G   C 0.999596 -3.675855 0.906064 -5.451740 -1.899970
2:  chr1:823032:C:T   C   T 0.006931  1.053056 0.264518  0.534601  1.571511
3:  chr1:834901:T:A   T   A 0.001039  1.771236 0.444135  0.900731  2.641741
4:  chr1:968677:G:C   C   G 0.999528 -2.933646 0.677918 -4.262365 -1.604927
5: chr1:1065477:G:A   A   G 0.999582 -3.695773 0.670812 -5.010565 -2.380981
6: chr1:1065478:C:A   A   C 0.999601 -3.494938 0.753512 -4.971822 -2.018054
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.056949 5.02e-05     4.298898     0     1 NaN         1     27239
2:  3.981037 6.93e-05     4.159246     0     1 NaN         1     85340
3:  3.988058 6.73e-05     4.172061     0     1   0         1     86172
4: -4.327435 1.53e-05     4.815903     0     1 NaN         1     27556
5: -5.509402 3.69e-08     7.433409     0     1 NaN         1     27541
6: -4.638198 3.57e-06     5.447433     0     1 NaN         1     27541
   Direction
1:      ??-?
2:      ?+??
3:      ?+??
4:      ??-?
5:      ??-?
6:      ??-?

#SNP in GWAS Summary:  138126
Overall with Annotation:  138126
Combined  138126
2421
11
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
3: chr1:835427:C:G   G   C 0.998818 -2.351023 0.554729 -3.438292 -1.263753
4: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
5: chr1:855362:C:T   T   C 0.999811 -3.836126 0.770500 -5.346306 -2.325946
6: chr1:905992:G:A   A   G 0.999811 -3.610069 0.900788 -5.375613 -1.844525
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.024650 5.77e-05     4.239187 0.000000 1.000000      NaN         1
2: -4.093935 4.29e-05     4.367804 0.000000 1.000000 0.000000         1
3: -4.238144 2.28e-05     4.641879 2.162101 0.141451 0.537487         2
4: -4.172480 3.05e-05     4.516012 0.000000 1.000000      NaN         1
5: -4.978749 6.52e-07     6.185814 0.000000 1.000000      NaN         1
6: -4.007679 6.19e-05     4.207986 0.000000 1.000000      NaN         1
   N_Samples Direction
1:     68595       ?-?
2:     68614       ?-?
3:    113865       ?-+
4:     68615       ?-?
5:     68617       ?-?
6:     68603       ?-?

#SNP in GWAS Summary:  249715
Overall with Annotation:  249715
Combined  249715
2643
12
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.UKBB450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
3: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
4: chr1:905992:G:A   A   G 0.999811 -3.610069 0.900788 -5.375613 -1.844525
5: chr1:917006:C:T   T   C 0.999577 -2.830286 0.695489 -4.193444 -1.467128
6: chr1:944681:C:T   T   C 0.999665 -3.717924 0.701207 -5.092290 -2.343558
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.024650 5.77e-05     4.239187     0     1 NaN         1     68595
2: -4.093935 4.29e-05     4.367804     0     1   0         1     68614
3: -4.172480 3.05e-05     4.516012     0     1 NaN         1     68615
4: -4.007679 6.19e-05     4.207986     0     1 NaN         1     68603
5: -4.069491 4.76e-05     4.322201     0     1 NaN         1     68616
6: -5.302178 1.17e-07     6.932109     0     1 NaN         1     68614
   Direction
1:      ??-?
2:      ??-?
3:      ??-?
4:      ??-?
5:      ??-?
6:      ??-?

#SNP in GWAS Summary:  473297
Overall with Annotation:  473297
Combined  473297
2412
13
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.ukbb200k_ukb250k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:826742:T:C   T   C 0.000049  3.457193 0.792858  1.903191  5.011195
3: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
4: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
5: chr1:849938:T:C   T   C 0.000045  3.263489 0.747890  1.797625  4.729353
6: chr1:851048:G:T   G   T 0.000240  2.681253 0.506355  1.688797  3.673708
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.024650 5.77e-05     4.239187 0.000000 1.000000      NaN         1
2:  4.360419 1.32e-05     4.881025 0.000000 1.000000      NaN         1
3: -4.093935 4.29e-05     4.367804 0.000000 1.000000 0.000000         1
4: -4.172480 3.05e-05     4.516012 0.000000 1.000000      NaN         1
5:  4.363595 1.30e-05     4.887319 0.000000 1.000000      NaN         1
6:  5.295205 1.21e-07     6.915556 2.697433 0.259573 0.258554         3
   N_Samples Direction
1:     68595     ???-?
2:    227291     ?+???
3:     68614     ???-?
4:     68615     ???-?
5:    227291     ?+???
6:    341154     ?+?+-

#SNP in GWAS Summary:  523713
Overall with Annotation:  523713
Combined  523713
2396
14
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.ukbb450k.ukb200k_N193342.ukb250k_N243350.tsv.gz
             SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:826742:T:C   T   C 0.000049 3.457193 0.792858 1.903191 5.011195
2: chr1:849938:T:C   T   C 0.000045 3.263489 0.747890 1.797625 4.729353
3: chr1:851048:G:T   G   T 0.000046 3.728087 0.945507 1.874893 5.581281
4: chr1:898406:C:T   C   T 0.000047 3.107279 0.775660 1.586985 4.627573
5: chr1:936104:C:T   C   T 0.000048 4.191775 0.826222 2.572380 5.811170
6: chr1:986717:C:T   C   T 0.000309 2.465500 0.589411 1.310254 3.620747
          Z        P minusLOG10_P    Het_Q    Het_P  I2 N_Studies N_Samples
1: 4.360419 1.32e-05     4.881025 0.000000 1.000000 NaN         1    227291
2: 4.363595 1.30e-05     4.887319 0.000000 1.000000 NaN         1    227291
3: 3.942950 8.13e-05     4.090075 0.000000 1.000000 NaN         1    227291
4: 4.005981 6.24e-05     4.204871 0.000000 1.000000   0         1    227291
5: 5.073425 3.98e-07     6.399723 0.000000 1.000000 NaN         1    227291
6: 4.182987 2.91e-05     4.536033 0.771214 0.379842   0         2    409711
   Direction
1:        ?+
2:        ?+
3:        ?+
4:        ?+
5:        ?+
6:        ++

#SNP in GWAS Summary:  369990
Overall with Annotation:  369990
Combined  369990
468
15
pval_0.0001.GWAMA.chr1_22.hasCH.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:969341:A:T   T   A 0.999295 -2.162973 0.534084 -3.209778 -1.116168
2: chr1:1051696:C:T   T   C 0.999425 -2.286489 0.581976 -3.427162 -1.145816
3: chr1:1686316:T:C   C   T 0.998120 -1.416984 0.358953 -2.120532 -0.713436
4: chr1:2925163:G:A   A   G 0.999452 -2.253087 0.542778 -3.316932 -1.189242
5: chr1:2947500:C:T   T   C 0.999452 -2.253072 0.542779 -3.316919 -1.189225
6: chr1:2961747:C:A   A   C 0.999373 -2.149339 0.526925 -3.182112 -1.116566
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.049874 5.18e-05     4.285783     0     1 NaN         1     19150
2: -3.928837 8.62e-05     4.064596     0     1 NaN         1     19146
3: -3.947547 7.97e-05     4.098392     0     1 NaN         1     19146
4: -4.151029 3.35e-05     4.475282     0     1 NaN         1     19147
5: -4.150993 3.35e-05     4.475215     0     1 NaN         1     19150
6: -4.079023 4.57e-05     4.339954     0     1 NaN         1     19145
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  14960
Overall with Annotation:  14960
Combined  14960
351
16
pval_0.0001.GWAMA.chr1_22.hasCH.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U

## EAF<=0.1%

In [26]:
rm(d, dat)

for(i in 1:length(gwas_files)){
    
    ##
    cat(i,"\n")
    cat(gwas_files[i], "\n")
    ##

    d <- fread(gwas_files[i], header=T)
    
    print(head(d))
    cat("\n")
    cat("#SNP in GWAS Summary: ",nrow(d), "\n")

###
    cat("Overall with Annotation: ",table(d$SNPID %in% annot$Otherinfo6, exclude=NULL), "\n")

###
    dat <- merge(d, annot, 
                 by.x="SNPID", 
                 by.y="Otherinfo6", 
                 all.x=TRUE)
    cat("Combined ",nrow(dat), "\n")    
    
    dat <- dat %>% filter(P<5e-7 & (AAF<=0.001 | AAF>=0.999) )
    cat(nrow(dat), "\n")
###
    outfile_name <- paste0("/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/GWAMA/summary/annovar/eafBlow001/blow_eaf001p5e7.annovar.", 
                           gsub(pattern = "tsv.gz", 
                           replacement = "csv", 
                           x = gwas_files[i]))
    
    fwrite(x = dat, file = outfile_name, 
           row.names = FALSE, 
           col.names = TRUE, 
           sep=",", 
           quote=TRUE)
    ##
    rm(dat,d, outfile_name)
    
}

Warning message in rm(d, dat):
"object 'd' not found"
Warning message in rm(d, dat):
"object 'dat' not found"

1
pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
               SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:   chr1:922263:G:A   A   G 0.999149 -3.095402 0.794578 -4.652775 -1.538029
2:  chr1:1018367:C:T   T   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
3:  chr1:1020894:G:C   C   G 0.999422 -3.716390 0.945653 -5.569870 -1.862910
4:  chr1:1037333:C:G   G   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
5:  chr1:1100572:C:G   G   C 0.999095 -3.747777 0.905251 -5.522069 -1.973485
6: chr1:1150280:AG:A   A  AG 0.999451 -4.274670 1.026446 -6.286504 -2.262836
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -3.895655 9.89e-05     4.005014     0     1 NaN         1     18220
2: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18221
3: -3.929972 8.58e-05     4.066642     0     1   0         1     18153
4: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18222
5: -4.140042 3.51e-05     4.454495     0     1 NaN         1     18223
6: -4.164535 3.16e-05     4.500904     0     1 NaN         1     18210
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  86309
Overall with Annotation:  86309
Combined  86309
1149
2
pval_0.0001.GWAMA.chr1_22.hasASXL1.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:   chr1:55427:T:C   T   C 0.006066  1.565527 0.361530  0.856928  2.274126
2:   chr1:87421:G:T   G   T 0.001070  2.297891 0.514283  1.289896  3.305886
3:   chr1:94970:C:T   C   T 0.001290  2.141355 0.476541  1.207335  3.075375
4:  chr1:922263:G:A   A   G 0.999149 -3.095402 0.794578 -4.652775 -1.538029
5: chr1:1018367:C:T   T   C 0.999424 -3.716602 0.945586 -5.569951 -1.863253
6: chr1:1020894:G:C   C   G 0.999422 -3.716390 0.945653 -5.569870 -1.862910
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1:  4.330282 1.51e-05     4.821507     0     1 NaN         1     41956
2:  4.468145 8.00e-06     5.096868     0     1 NaN         1     43443
3:  4.493538 7.10e-06     5.148450     0     1 NaN         1     43810
4: -3.895655 9.89e-05     4.005014     0     1 NaN         1     18220
5: -3.930475 8.56e-05     4.067548     0     1 NaN         1     18221
6: -3.929972 8.58e-05     4.066642     0     1   0         1     18153
   Direction
1:      ?+??
2:      ?+??
3:      ?+??
4:      ??-?
5:      ??-?
6:      ??-?

#SNP in GWAS Summary:  90101
Overall with Annotation:  90101
Combined  90101
1147
3
pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:768968:C:T   T   C 0.998615 -3.768046 0.956303 -5.642400 -1.893692
2: chr1:1381907:G:A   A   G 0.998436 -4.229041 1.047881 -6.282888 -2.175194
3: chr1:1452554:G:C   C   G 0.998044 -3.108008 0.790348 -4.657090 -1.558926
4: chr1:1487254:C:T   T   C 0.998369 -4.219628 1.044464 -6.266777 -2.172479
5: chr1:1538006:G:A   A   G 0.998436 -4.225581 1.046601 -6.276919 -2.174243
6: chr1:2112271:C:A   A   C 0.998632 -3.609548 0.923263 -5.419143 -1.799953
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -3.940222 8.22e-05     4.085143     0     1 NaN         1      7582
2: -4.035803 5.50e-05     4.259757     0     1 NaN         1      7673
3: -3.932455 8.49e-05     4.071119     0     1 NaN         1      7667
4: -4.039994 5.40e-05     4.267500     0     1 NaN         1      7663
5: -4.037433 5.46e-05     4.262767     0     1 NaN         1      7673
6: -3.909556 9.33e-05     4.029918     0     1 NaN         1      7673
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  30242
Overall with Annotation:  30242
Combined  30242
0
4
pval_0.0001.GWAMA.chr1_22.hasASXL1.AMR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
                  SNPID   REF ALT      AAF      BETA       SE  BETA_95L
1:      chr1:768968:C:T     T   C 0.998615 -3.768046 0.956303 -5.642400
2:      chr1:978225:C:T     C   T 0.002936  4.733486 1.166920  2.446323
3:     chr1:1192820:G:A     G   A 0.002609  3.014204 0.691412  1.659036
4:     chr1:1207207:G:A     G   A 0.001921  3.426385 0.641773  2.168510
5: chr1:1221953:AAAAG:A AAAAG   A 0.001606  3.189654 0.792666  1.636029
6:     chr1:1243468:G:A     G   A 0.001858  3.300963 0.747688  1.835496
    BETA_95U         Z        P minusLOG10_P    Het_Q    Het_P       I2
1: -1.893692 -3.940222 8.22e-05     4.085143 0.000000 1.000000      NaN
2:  7.020649  4.056393 5.04e-05     4.297868 0.936726 0.333121 0.000000
3:  4.369372  4.359490 1.32e-05     4.879186 0.000000 1.000000      NaN
4:  4.684260  5.338936 9.56e-08     7.019712 0.000000 1.000000      NaN
5:  4.743279  4.023957 5.78e-05     4.237912 2.636615 0.104426 0.620726
6:  4.766431  4.414897 1.02e-05     4.989575 1.770101 0.183370 0.435060
   N_Studies N_Samples Direction
1:         1      7582      ??-?
2:         2     39243      ?+?+
3:         1     30285      ?+??
4:         1     35914      ?+??
5:         2     43587      ?-+?
6:         2     43588      ?++?

#SNP in GWAS Summary:  32565
Overall with Annotation:  32565
Combined  32565
0
5
pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
                 SNPID REF  ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:    chr1:1091539:G:A   A    G 0.999736 -3.380540 0.740564 -4.832045 -1.929035
2:    chr1:1159165:A:G   G    A 0.999644 -2.935615 0.743929 -4.393716 -1.477514
3:    chr1:1182739:G:A   A    G 0.999631 -2.972972 0.762393 -4.467262 -1.478681
4:    chr1:1203315:C:T   T    C 0.999617 -3.602360 0.811457 -5.192816 -2.011904
5:    chr1:1254595:G:A   A    G 0.999617 -3.437272 0.868261 -5.139064 -1.735480
6: chr1:1266828:AAAT:A   A AAAT 0.998527 -1.912470 0.423309 -2.742156 -1.082784
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.564818 5.07e-06     5.294680 0.000000 1.000000      NaN         1
2: -3.946096 8.02e-05     4.095765 0.000000 1.000000      NaN         1
3: -3.899526 9.73e-05     4.011941 0.111421 0.738532 0.000000         2
4: -4.439373 9.15e-06     5.038746 0.000000 1.000000      NaN         1
5: -3.958800 7.61e-05     4.118788 0.000000 1.000000      NaN         1
6: -4.517904 6.34e-06     5.198198 1.568439 0.210434 0.362423         2
   N_Samples Direction
1:     37880       ?-?
2:     37884       ?-?
3:     75662       ?--
4:     37876       ?-?
5:     37881       ?-?
6:     75664       ?--

#SNP in GWAS Summary:  51327
Overall with Annotation:  51327
Combined  51327
2347
6
pval_0.0001.GWAMA.chr1_22.hasASXL1.EUR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:1126159:C:T   C   T 0.000038 2.755898 0.705637 1.372849 4.138947
2: chr1:1143606:G:A   G   A 0.000145 2.290563 0.547329 1.217798 3.363328
3: chr1:1147746:G:A   G   A 0.000042 3.797108 0.794134 2.240605 5.353611
4: chr1:1171708:G:A   G   A 0.000506 1.349660 0.340715 0.681858 2.017462
5: chr1:1172226:G:A   G   A 0.000281 2.233030 0.527918 1.198311 3.267749
6: chr1:1180415:G:A   G   A 0.000042 3.000572 0.768786 1.493751 4.507393
          Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: 3.905546 9.49e-05     4.022727 0.000000 1.000000      NaN         1
2: 4.184984 2.89e-05     4.539842 0.000000 1.000000      NaN         1
3: 4.781445 1.77e-06     5.752105 0.000000 1.000000 0.000000         1
4: 3.961257 7.53e-05     4.123247 7.481134 0.023741 0.732661         3
5: 4.229883 2.37e-05     4.625944 0.787791 0.374769 0.000000         2
6: 3.903000 9.59e-05     4.018164 0.000000 1.000000 0.000000         1
   N_Samples Direction
1:    388018      +???
2:    388018      +???
3:    388018      +???
4:    463667      +?+-
5:    425899      +?+?
6:    388018      +???

#SNP in GWAS Summary:  244294
Overall with Annotation:  244294
Combined  244294
15155
7
pval_0.0001.GWAMA.chr1_22.hasASXL1.Female.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:769499:G:C   G   C 0.000522  4.195042 1.045107  2.146632  6.243452
2: chr1:780466:G:A   A   G 0.998762 -2.922156 0.627831 -4.152704 -1.691607
3: chr1:793267:C:T   T   C 0.998779 -2.922419 0.624943 -4.147307 -1.697531
4: chr1:794072:C:T   T   C 0.998787 -2.933263 0.626271 -4.160754 -1.705772
5: chr1:795717:G:A   A   G 0.998779 -2.913844 0.627522 -4.143786 -1.683902
6: chr1:796639:C:T   T   C 0.998779 -2.922420 0.624943 -4.147308 -1.697532
           Z        P minusLOG10_P    Het_Q    Het_P  I2 N_Studies N_Samples
1:  4.013983 6.03e-05     4.219563 0.000000 1.000000 NaN         1     25335
2: -4.654367 3.30e-06     5.481392 0.435123 0.509486   0         2     66395
3: -4.676298 2.97e-06     5.527630 0.383258 0.535865   0         2     66396
4: -4.683696 2.86e-06     5.543272 0.417528 0.518173   0         2     66396
5: -4.643416 3.48e-06     5.458380 0.446790 0.503863   0         2     66398
6: -4.676299 2.97e-06     5.527632 0.383257 0.535865   0         2     66397
   Direction
1:       ??+
2:       ?--
3:       ?--
4:       ?--
5:       ?--
6:       ?--

#SNP in GWAS Summary:  220139
Overall with Annotation:  220139
Combined  220139
10317
8
pval_0.0001.GWAMA.chr1_22.hasASXL1.Female.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:824903:C:G   C   G 0.000418 3.013057 0.644678 1.749489 4.276625
2: chr1:825872:C:T   C   T 0.000481 2.759369 0.642608 1.499857 4.018881
3: chr1:829566:T:C   T   C 0.000414 3.015629 0.645013 1.751405 4.279854
4: chr1:832823:C:T   C   T 0.000438 3.495835 0.891218 1.749047 5.242622
5: chr1:837890:G:T   G   T 0.000447 2.995344 0.641076 1.738835 4.251854
6: chr1:841202:A:G   A   G 0.000416 3.014542 0.644780 1.750774 4.278310
          Z        P minusLOG10_P    Het_Q    Het_P      I2 N_Studies N_Samples
1: 4.673742 3.00e-06     5.522232 0.618324 0.734062 0.00000         3    287583
2: 4.294014 1.78e-05     4.750378 1.079622 0.582858 0.00000         3    287583
3: 4.675303 2.98e-06     5.525527 0.606722 0.738333 0.00000         3    287581
4: 3.922535 8.85e-05     4.053245 2.326556 0.312460 0.14036         3    287525
5: 4.672367 3.02e-06     5.519328 0.623087 0.732316 0.00000         3    287576
6: 4.675305 2.98e-06     5.525533 0.610431 0.736964 0.00000         3    287583
   Direction
1:      +?++
2:      +?++
3:      +?++
4:      +?++
5:      +?++
6:      +?++

#SNP in GWAS Summary:  298176
Overall with Annotation:  298176
Combined  298176
19816
9
pval_0.0001.GWAMA.chr1_22.hasASXL1.Male.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:776729:C:G   G   C 0.999596 -3.675855 0.906064 -5.451740 -1.899970
2:  chr1:835427:C:G   G   C 0.998186 -2.750612 0.616365 -3.958687 -1.542537
3:  chr1:968677:G:C   C   G 0.999528 -2.933646 0.677918 -4.262365 -1.604927
4:  chr1:975749:G:A   A   G 0.999601 -3.697585 0.947577 -5.554836 -1.840334
5: chr1:1065477:G:A   A   G 0.999582 -3.695773 0.670812 -5.010565 -2.380981
6: chr1:1065478:C:A   A   C 0.999601 -3.494938 0.753512 -4.971822 -2.018054
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.056949 5.02e-05     4.298898     0     1 NaN         1     27239
2: -4.462635 8.21e-06     5.085711     0     1 NaN         1     27556
3: -4.327435 1.53e-05     4.815903     0     1 NaN         1     27556
4: -3.902147 9.62e-05     4.016635     0     1 NaN         1     27552
5: -5.509402 3.69e-08     7.433409     0     1 NaN         1     27541
6: -4.638198 3.57e-06     5.447433     0     1 NaN         1     27541
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  90597
Overall with Annotation:  90597
Combined  90597
2713
10
pval_0.0001.GWAMA.chr1_22.hasASXL1.Male.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:776729:C:G   G   C 0.999596 -3.675855 0.906064 -5.451740 -1.899970
2:  chr1:823032:C:T   C   T 0.006931  1.053056 0.264518  0.534601  1.571511
3:  chr1:834901:T:A   T   A 0.001039  1.771236 0.444135  0.900731  2.641741
4:  chr1:968677:G:C   C   G 0.999528 -2.933646 0.677918 -4.262365 -1.604927
5: chr1:1065477:G:A   A   G 0.999582 -3.695773 0.670812 -5.010565 -2.380981
6: chr1:1065478:C:A   A   C 0.999601 -3.494938 0.753512 -4.971822 -2.018054
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.056949 5.02e-05     4.298898     0     1 NaN         1     27239
2:  3.981037 6.93e-05     4.159246     0     1 NaN         1     85340
3:  3.988058 6.73e-05     4.172061     0     1   0         1     86172
4: -4.327435 1.53e-05     4.815903     0     1 NaN         1     27556
5: -5.509402 3.69e-08     7.433409     0     1 NaN         1     27541
6: -4.638198 3.57e-06     5.447433     0     1 NaN         1     27541
   Direction
1:      ??-?
2:      ?+??
3:      ?+??
4:      ??-?
5:      ??-?
6:      ??-?

#SNP in GWAS Summary:  138126
Overall with Annotation:  138126
Combined  138126
6668
11
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
3: chr1:835427:C:G   G   C 0.998818 -2.351023 0.554729 -3.438292 -1.263753
4: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
5: chr1:855362:C:T   T   C 0.999811 -3.836126 0.770500 -5.346306 -2.325946
6: chr1:905992:G:A   A   G 0.999811 -3.610069 0.900788 -5.375613 -1.844525
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.024650 5.77e-05     4.239187 0.000000 1.000000      NaN         1
2: -4.093935 4.29e-05     4.367804 0.000000 1.000000 0.000000         1
3: -4.238144 2.28e-05     4.641879 2.162101 0.141451 0.537487         2
4: -4.172480 3.05e-05     4.516012 0.000000 1.000000      NaN         1
5: -4.978749 6.52e-07     6.185814 0.000000 1.000000      NaN         1
6: -4.007679 6.19e-05     4.207986 0.000000 1.000000      NaN         1
   N_Samples Direction
1:     68595       ?-?
2:     68614       ?-?
3:    113865       ?-+
4:     68615       ?-?
5:     68617       ?-?
6:     68603       ?-?

#SNP in GWAS Summary:  249715
Overall with Annotation:  249715
Combined  249715
21905
12
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.UKBB450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
3: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
4: chr1:905992:G:A   A   G 0.999811 -3.610069 0.900788 -5.375613 -1.844525
5: chr1:917006:C:T   T   C 0.999577 -2.830286 0.695489 -4.193444 -1.467128
6: chr1:944681:C:T   T   C 0.999665 -3.717924 0.701207 -5.092290 -2.343558
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.024650 5.77e-05     4.239187     0     1 NaN         1     68595
2: -4.093935 4.29e-05     4.367804     0     1   0         1     68614
3: -4.172480 3.05e-05     4.516012     0     1 NaN         1     68615
4: -4.007679 6.19e-05     4.207986     0     1 NaN         1     68603
5: -4.069491 4.76e-05     4.322201     0     1 NaN         1     68616
6: -5.302178 1.17e-07     6.932109     0     1 NaN         1     68614
   Direction
1:      ??-?
2:      ??-?
3:      ??-?
4:      ??-?
5:      ??-?
6:      ??-?

#SNP in GWAS Summary:  473297
Overall with Annotation:  473297
Combined  473297
47853
13
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.ukbb200k_ukb250k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
             SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1: chr1:772150:C:A   A   C 0.999825 -3.727405 0.926144 -5.542647 -1.912163
2: chr1:826742:T:C   T   C 0.000049  3.457193 0.792858  1.903191  5.011195
3: chr1:830971:G:A   A   G 0.999796 -3.685041 0.900122 -5.449280 -1.920802
4: chr1:848535:T:C   C   T 0.999548 -2.913989 0.698383 -4.282820 -1.545158
5: chr1:849938:T:C   T   C 0.000045  3.263489 0.747890  1.797625  4.729353
6: chr1:851048:G:T   G   T 0.000240  2.681253 0.506355  1.688797  3.673708
           Z        P minusLOG10_P    Het_Q    Het_P       I2 N_Studies
1: -4.024650 5.77e-05     4.239187 0.000000 1.000000      NaN         1
2:  4.360419 1.32e-05     4.881025 0.000000 1.000000      NaN         1
3: -4.093935 4.29e-05     4.367804 0.000000 1.000000 0.000000         1
4: -4.172480 3.05e-05     4.516012 0.000000 1.000000      NaN         1
5:  4.363595 1.30e-05     4.887319 0.000000 1.000000      NaN         1
6:  5.295205 1.21e-07     6.915556 2.697433 0.259573 0.258554         3
   N_Samples Direction
1:     68595     ???-?
2:    227291     ?+???
3:     68614     ???-?
4:     68615     ???-?
5:    227291     ?+???
6:    341154     ?+?+-

#SNP in GWAS Summary:  523713
Overall with Annotation:  523713
Combined  523713
52087
14
pval_0.0001.GWAMA.chr1_22.hasASXL1.MultiANC.ukbb450k.ukb200k_N193342.ukb250k_N243350.tsv.gz
             SNPID REF ALT      AAF     BETA       SE BETA_95L BETA_95U
1: chr1:826742:T:C   T   C 0.000049 3.457193 0.792858 1.903191 5.011195
2: chr1:849938:T:C   T   C 0.000045 3.263489 0.747890 1.797625 4.729353
3: chr1:851048:G:T   G   T 0.000046 3.728087 0.945507 1.874893 5.581281
4: chr1:898406:C:T   C   T 0.000047 3.107279 0.775660 1.586985 4.627573
5: chr1:936104:C:T   C   T 0.000048 4.191775 0.826222 2.572380 5.811170
6: chr1:986717:C:T   C   T 0.000309 2.465500 0.589411 1.310254 3.620747
          Z        P minusLOG10_P    Het_Q    Het_P  I2 N_Studies N_Samples
1: 4.360419 1.32e-05     4.881025 0.000000 1.000000 NaN         1    227291
2: 4.363595 1.30e-05     4.887319 0.000000 1.000000 NaN         1    227291
3: 3.942950 8.13e-05     4.090075 0.000000 1.000000 NaN         1    227291
4: 4.005981 6.24e-05     4.204871 0.000000 1.000000   0         1    227291
5: 5.073425 3.98e-07     6.399723 0.000000 1.000000 NaN         1    227291
6: 4.182987 2.91e-05     4.536033 0.771214 0.379842   0         2    409711
   Direction
1:        ?+
2:        ?+
3:        ?+
4:        ?+
5:        ?+
6:        ++

#SNP in GWAS Summary:  369990
Overall with Annotation:  369990
Combined  369990
32781
15
pval_0.0001.GWAMA.chr1_22.hasCH.AFR.AoU250k_TOPMed72k_MGBB53k.noukbb.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U
1:  chr1:969341:A:T   T   A 0.999295 -2.162973 0.534084 -3.209778 -1.116168
2: chr1:1051696:C:T   T   C 0.999425 -2.286489 0.581976 -3.427162 -1.145816
3: chr1:1686316:T:C   C   T 0.998120 -1.416984 0.358953 -2.120532 -0.713436
4: chr1:2925163:G:A   A   G 0.999452 -2.253087 0.542778 -3.316932 -1.189242
5: chr1:2947500:C:T   T   C 0.999452 -2.253072 0.542779 -3.316919 -1.189225
6: chr1:2961747:C:A   A   C 0.999373 -2.149339 0.526925 -3.182112 -1.116566
           Z        P minusLOG10_P Het_Q Het_P  I2 N_Studies N_Samples
1: -4.049874 5.18e-05     4.285783     0     1 NaN         1     19150
2: -3.928837 8.62e-05     4.064596     0     1 NaN         1     19146
3: -3.947547 7.97e-05     4.098392     0     1 NaN         1     19146
4: -4.151029 3.35e-05     4.475282     0     1 NaN         1     19147
5: -4.150993 3.35e-05     4.475215     0     1 NaN         1     19150
6: -4.079023 4.57e-05     4.339954     0     1 NaN         1     19145
   Direction
1:       ?-?
2:       ?-?
3:       ?-?
4:       ?-?
5:       ?-?
6:       ?-?

#SNP in GWAS Summary:  14960
Overall with Annotation:  14960
Combined  14960
103
16
pval_0.0001.GWAMA.chr1_22.hasCH.AFR.ukbb450k_AoU250k_TOPMed72k_MGBB53k.tsv.gz
              SNPID REF ALT      AAF      BETA       SE  BETA_95L  BETA_95U